### ISSUE TITLE
Status of suricata/tilera with suricata 2.0.x and TileraMDE 4.3.x?

### ISSUE THREAD

**Issue by changwoo** [decanio/suricata-tilera#2]
The wiki page https://github.com/decanio/suricata/wiki/Suricata-for-Tilera contains old information. Now Tilera is working on the upstream so suricata 2.0.x contains tilera support. But I have found no updated information on using this newer version with the recent TileraMDE 4.3.x.

Please update the page if you can, or direct me to updated info if any.

**Comment by decanio** [comment]
Changwoo.  I've not maintained this copy of suricata for Tilera for quite some time now.  You should contact Tilera for instructions on operating suricata on their hardware.

**Comment by ken-tilera** [comment]
Please email suricata@tilera.com for help.
